[
    {
        "img": "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        "id": "4c616175-5e46-5f0e-a418-621daf089faa",
        "title": "Nike Air Monarch IV",
        "reviews": "116 reviews",
        "prevPrice": "$140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "white",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        "id": "9b38c9e0-a36b-5509-bd20-bc74ec7334f9",
        "title": "Nike Air Vapormax Plus",
        "reviews": "106 reviews",
        "prevPrice": "$140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "red",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
        "id": "4f8437d4-46f1-5aed-9424-d7a23ac126f6",
        "title": "Nike Waffle One Sneaker",
        "reviews": "71 reviews",
        "prevPrice": "$140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "green",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
        "id": "6097ffc3-408a-5b5a-a8c6-0d4f5637e42c",
        "title": "Nike Running Shoe",
        "reviews": "47 reviews",
        "prevPrice": "$140,00",
        "newPrice": "200",
        "company": "Adidas",
        "color": "black",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
        "id": "52dbf432-5b9d-552c-88ac-d08282593b1f",
        "title": "Flat Slip On Pumps",
        "reviews": "35 reviews",
        "prevPrice": "$140,00",
        "newPrice": "200",
        "company": "Vans",
        "color": "green",
        "category": "flats"
    },
    {
        "img": "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
        "id": "91850a96-4800-5322-90c0-cb018e1bfacc",
        "title": "Knit Ballet Flat",
        "reviews": "76 reviews",
        "prevPrice": "$140,00",
        "newPrice": "50",
        "company": "Adidas",
        "color": "black",
        "category": "flats"
    },
    {
        "img": "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
        "id": "84dc71b5-09e8-519c-83ab-c4b75a29f08a",
        "title": "Loafer Flats",
        "reviews": "34 reviews",
        "prevPrice": "$140,00",
        "newPrice": "50",
        "company": "Vans",
        "color": "white",
        "category": "flats"
    },
    {
        "img": "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
        "id": "ee767aa0-92da-5f4a-8710-c54dbec5ae05",
        "title": "Nike Zoom Freak",
        "reviews": "89 reviews",
        "prevPrice": "$140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "green",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
        "id": "23c2260b-faea-55bb-8a71-ef7a15b1d994",
        "title": "Nike Men's Sneaker",
        "reviews": "116 reviews",
        "prevPrice": "$140,00",
        "newPrice": "200",
        "company": "Adidas",
        "color": "blue",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        "id": "2fe80d63-ad83-5784-baf0-3416b74af597",
        "title": "PUMA BLACK-OCE",
        "reviews": "120 reviews",
        "prevPrice": "$140,00",
        "newPrice": "150",
        "company": "Puma",
        "color": "green",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
        "id": "f62e5139-0b17-5f93-afba-5c72cdc7b065",
        "title": "Pacer Future Sneaker",
        "reviews": "38 reviews",
        "prevPrice": "$140,00",
        "newPrice": "150",
        "company": "Puma",
        "color": "red",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
        "id": "550bba8f-d7fa-5fa7-acce-f2ac6f8691df",
        "title": "Unisex-Adult Super",
        "reviews": "115 reviews",
        "prevPrice": "$140,00",
        "newPrice": "150",
        "company": "Puma",
        "color": "black",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
        "id": "0572bcf8-17ec-5dd2-88bb-3499aff0d8f4",
        "title": "Roma Basic Sneaker",
        "reviews": "109 reviews",
        "prevPrice": "$140,00",
        "newPrice": "150",
        "company": "Puma",
        "color": "white",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
        "id": "02bf9a82-df75-5d2d-9ccd-46a5dbaf41db",
        "title": "Pacer Future Doubleknit",
        "reviews": "66 reviews",
        "prevPrice": "$140,00",
        "newPrice": "150",
        "company": "Puma",
        "color": "black",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        "id": "b2caf4a9-52de-58c0-9d8d-211e582da2be",
        "title": "Fusion Evo Golf Shoe",
        "reviews": "52 reviews",
        "prevPrice": "$140,00",
        "newPrice": "100",
        "company": "Puma",
        "color": "green",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
        "id": "f4c5d551-ddb3-5d33-9994-4e5c3b3fc99e",
        "title": "Rainbow Chex Skate",
        "reviews": "112 reviews",
        "prevPrice": "$140,00",
        "newPrice": "100",
        "company": "Vans",
        "color": "red",
        "category": "flats"
    },
    {
        "img": "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
        "id": "40adc20e-230b-5082-8794-733b6f565c2f",
        "title": "Low-Top Trainers",
        "reviews": "117 reviews",
        "prevPrice": "$140,00",
        "newPrice": "100",
        "company": "Vans",
        "color": "white",
        "category": "sandals"
    },
    {
        "img": "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
        "id": "1d0140c0-5461-5a1f-a462-1a8447709797",
        "title": "Vans Unisex Low-Top",
        "reviews": "38 reviews",
        "prevPrice": "$140,00",
        "newPrice": "100",
        "company": "Vans",
        "color": "blue",
        "category": "sandals"
    },
    {
        "img": "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
        "id": "ddfc716d-0c40-5f0e-a7e0-111b59a710df",
        "title": "Classic Bandana Sneakers",
        "reviews": "100 reviews",
        "prevPrice": "$140,00",
        "newPrice": "50",
        "company": "Nike",
        "color": "black",
        "category": "sandals"
    },
    {
        "img": "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
        "id": "0d8045bb-8450-52eb-98b8-6a8539882033",
        "title": "Chunky High Heel",
        "reviews": "47 reviews",
        "prevPrice": "$140,00",
        "newPrice": "50",
        "company": "Vans",
        "color": "black",
        "category": "heels"
    },
    {
        "img": "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
        "id": "bc2a1dd6-c637-54ad-b88b-c1e709481c61",
        "title": "Slip On Stiletto High Heel",
        "reviews": "39 reviews",
        "prevPrice": "$140,00",
        "newPrice": "100",
        "company": "puma",
        "color": "black",
        "category": "heels"
    },
    {
        "img": "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
        "id": "908d5d32-94db-5ba6-8da1-acf24442dec5",
        "title": "DREAM PAIRS Court Shoes",
        "reviews": "80 reviews",
        "prevPrice": "$140,00",
        "newPrice": "150",
        "company": "Nike",
        "color": "red",
        "category": "heels"
    },
    {
        "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        "id": "c0302488-a17e-5bc1-9a62-e15ec0230b52",
        "title": "Nike Air Vapormax Plus",
        "reviews": "68 reviews",
        "prevPrice": "$140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "red",
        "category": "sneakers"
    },
    {
        "img": "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
        "id": "29ca5002-bef3-5b7e-97e5-44a5db432377",
        "title": "Low Mid Block Heels",
        "reviews": "79 reviews",
        "prevPrice": "$140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "black",
        "category": "heels"
    },
    {
        "img": "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
        "id": "775d0b78-43c4-5909-a950-c690ca8d2a38",
        "title": "Chunky High Heel",
        "reviews": "75 reviews",
        "prevPrice": "$140,00",
        "newPrice": "50",
        "company": "Adidas",
        "color": "black",
        "category": "heels"
    },
    {
        "img": "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
        "id": "130f79c4-1262-5349-84b8-d9218bc55f0d",
        "title": "Amore Fashion Stilettos",
        "reviews": "90 reviews",
        "prevPrice": "$140,00",
        "newPrice": "150",
        "company": "Adidas",
        "color": "white",
        "category": "heels"
    },
    {
        "img": "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
        "id": "038124b2-1c9b-51b2-949b-2c59664e294e",
        "title": "Bridal Sandals Glitter",
        "reviews": "53 reviews",
        "prevPrice": "$140,00",
        "newPrice": "50",
        "company": "Adidas",
        "color": "black",
        "category": "heels"
    },
    {
        "img": "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
        "id": "e07c4e22-027a-57be-ad4a-16db99a3165e",
        "title": "Wedding Prom Bridal",
        "reviews": "82 reviews",
        "prevPrice": "$140,00",
        "newPrice": "50",
        "company": "Adidas",
        "color": "black",
        "category": "flats"
    }
]
